---
- file:
    path: /etc/ansible/roles
    state: directory

- git:
    repo: https://github.com/openshift/openshift-ansible.git
    dest: /etc/ansible/roles
    force: yes
    clone: yes
  register: CLONE
  
- shell: git checkout release-3.11 
  args:
    chdir: /etc/ansible/roles/openshift-ansible
  when: CLONE is success  

# TO MASTER /OSE
#docker pull registry.redhat.io/openshift3/ose-node:v3.11
#docker pull registry.redhat.io/openshift3/ose-node:v3.11.117
#docker pull registry.redhat.io/openshift3/ose-control-plane:v3.11
#docker pull registry.redhat.io/openshift3/ose-control-plane:v3.11.117
#docker pull registry.redhat.io/openshift3/ose-pod:v3.11
#docker pull registry.redhat.io/openshift3/ose-pod:v3.11.117
#docker pull registry.redhat.io/rhel7/etcd
#docker pull docker.io/cockpit/kubernetes:latest
#docker pull quay.io/coreos/etcd

# TO NODE /OSE
#docker pull registry.redhat.io/openshift3/ose-node:v3.11
#docker pull registry.redhat.io/openshift3/ose-node:v3.11.117
#docker pull registry.redhat.io/openshift3/ose-pod:v3.11
#docker pull registry.redhat.io/openshift3/ose-pod:v3.11.117
...