---
- file:
    path: /etc/ansible/roles
    state: directory

- git:
    repo: https://github.com/openshift/openshift-ansible.git
    dest: /etc/ansible/roles
    force: yes
    clone: yes
  register: CLONE
  
- shell: git checkout release-3.11 
  args:
    chdir: /etc/ansible/roles/openshift-ansible
  when: CLONE is success  


# TO MASTER
#docker pull docker.io/cockpit/kubernetes
#docker pull docker.io/openshift/origin-deployer:v3.11
#docker pull docker.io/openshift/origin-docker-registry:v3.11
#docker pull docker.io/openshift/origin-haproxy-router:v3.11
#docker pull docker.io/openshift/origin-pod:v3.11
#docker pull docker.io/openshift/origin-control-plane:v3.11
#docker pull quay.io/coreos/etcd:v3.2.22

# TO NODE
#docker pull docker.io/cockpit/kubernetes
#docker pull docker.io/openshift/origin-deployer:v3.11
#docker pull docker.io/openshift/origin-docker-registry:v3.11
#docker pull docker.io/openshift/origin-haproxy-router:v3.11
#docker pull docker.io/openshift/origin-pod:v3.11   
...

